builder:
  track: dev

labels:
  app: estafette-extension-dotnet
  app-group: estafette-ci-extensions
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master

stages:
  build:
    image: golang:1.13.0-alpine3.10
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go build -v -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake-2.1:
    image: extensions/docker:dev
    action: build
    container: dotnet
    repositories:
    - extensions
    path: ./publish
    noCache: true
    versionTagSuffix: v2.1-sdk
    env:
      SDK_VERSION_TAG: 2.1-sdk
    copy:
    - Dockerfile

  bake-2.2:
    image: extensions/docker:dev
    action: build
    container: dotnet
    repositories:
    - extensions
    path: ./publish
    noCache: true
    versionTagSuffix: v2.2-sdk
    env:
      SDK_VERSION_TAG: 2.2-sdk
    copy:
    - Dockerfile

  bake-3.0:
    image: extensions/docker:dev
    action: build
    container: dotnet
    repositories:
    - extensions
    path: ./publish
    noCache: true
    versionTagSuffix: v3.0-sdk
    env:
      SDK_VERSION_TAG: 3.0-sdk
    copy:
    - Dockerfile

  push-container-image-2.1:
    image: extensions/docker:dev
    action: push
    container: dotnet
    noCache: true
    versionTagSuffix: v2.1-sdk
    repositories:
    - extensions

  push-container-image-2.2:
    image: extensions/docker:dev
    action: push
    container: dotnet
    noCache: true
    versionTagSuffix: v2.2-sdk
    repositories:
    - extensions

  push-container-image-3.0:
    image: extensions/docker:dev
    action: push
    container: dotnet
    noCache: true
    versionTagSuffix: v3.0-sdk
    repositories:
    - extensions

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  dev:
    triggers:
    - pipeline:
        name: self
        branch: .+
    stages:
      tag-container-image-2.1:
        image: extensions/docker:dev
        action: tag
        container: dotnet
        versionTagSuffix: v2.1-sdk
        repositories:
        - extensions
        tags:
        - 2.1-dev

      tag-container-image-2.2:
        image: extensions/docker:dev
        action: tag
        container: dotnet
        versionTagSuffix: v2.2-sdk
        repositories:
        - extensions
        tags:
        - 2.2-dev

      tag-container-image-3.0:
        image: extensions/docker:dev
        action: tag
        container: dotnet
        versionTagSuffix: v3.0-sdk
        repositories:
        - extensions
        tags:
        - 3.0-dev

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  stable:
    stages:
      tag-container-image-2.1:
        image: extensions/docker:dev
        action: tag
        container: dotnet
        versionTagSuffix: v2.1-sdk
        repositories:
        - extensions
        tags:
        - 2.1-stable

      tag-container-image-2.2:
        image: extensions/docker:dev
        action: tag
        container: dotnet
        versionTagSuffix: v2.2-sdk
        repositories:
        - extensions
        tags:
        - 2.2-stable

      tag-container-image-3.0:
        image: extensions/docker:dev
        action: tag
        container: dotnet
        versionTagSuffix: v3.0-sdk
        repositories:
        - extensions
        tags:
        - 3.0-stable

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'