builder:
  track: dev

labels:
  app: estafette-extension-dotnet
  app-group: estafette-ci-extensions
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master

stages:
  build:
    image: golang:1.11.2-alpine3.8
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake:
    image: extensions/docker:stable
    action: build
    container: dotnet
    repositories:
    - extensions
    path: ./publish
    copy:
    - Dockerfile

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  dev:
    clone: true
    stages:
      build:
        image: golang:1.11.2-alpine3.8
        workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
        env:
          CGO_ENABLED: 0
          GOOS: linux
        commands:
        - go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .

      bake:
        image: extensions/docker:stable
        action: build
        container: dotnet
        repositories:
        - extensions
        path: ./publish
        copy:
        - Dockerfile

      push-container-image:
        image: extensions/docker:stable
        action: push
        container: dotnet
        repositories:
        - extensions
        tags:
        - dev

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  "2.1":
    clone: true
    stages:
      build:
        image: golang:1.11.2-alpine3.8
        workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
        env:
          CGO_ENABLED: 0
          GOOS: linux
        commands:
        - go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .

      bake:
        image: extensions/docker:stable
        action: build
        container: dotnet
        repositories:
        - extensions
        path: ./publish
        copy:
        - Dockerfile

      push-container-image:
        image: extensions/docker:stable
        action: push
        container: dotnet
        repositories:
        - extensions
        tags:
        - "2.1"

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'
